- Mirage-2000/Nasal/missile.nas
Fixed missile impact report was incompatible with Bombable.
Added telemetry link feedback to aircraft for certain missiles.
> Some missile updates

- Mirage-2000/Nasal/RADAR/radar2.nas
Fixed missile impact report was incompatible with Bombable.
Added telemetry link feedback to aircraft for certain missiles.
> Fixed that radar was using air2air doppler to see ground targets.

- Mirage-2000/Nasal/missile.nas
Missiles will now check if target is not obscured by terrain. (2017.2.1+)
> Missile picking

- Mirage-2000/Nasal/RADAR/radar2.nas
- Mirage-2000/Nasal/RADAR/target_class.nas
- Mirage-2000/Nasal/missile.nas
- Mirage-2000/Nasal/rcs.nas
- Mirage-2000/Nasal/vector.nas
- Mirage-2000/System/m2000-5-base.xml
- Mirage-2000/System/m2000-5B-base.xml
Hey.
Various improvements to missile.nas included.
RCS check for radar included.
> Added radar RCS check.

- Mirage-2000/Nasal/missile.nas
- Mirage-2000/Nasal/vector.nas
- Mirage-2000/System/payload.xml
Arms: Started building fading out of rocket thrust.
Arms: Made aim-9l terminate before its speed is so low it wont hit anything anyway. Aerodynamic range will then also better match published data.
Sim: Better commenting in getPitch method.
Fix for geo.Coord bad methods. If fix works, remember to send to FG mailing list.
Arms: Removed need for sound bools in weapons specs.
Arms: Renamed drag-area to cross-section.
Arms: Made check for seeker/FCS FOV round instead of square.
Arms: Renamed some nasal variables.
Arms: Better impulse output when uncommented.
Arms: Added support for vectored thrust.
Arms: Proportionality constant for PN/APN can now be specified.
Arms: Some cleanup of code and comments.
Sim: Finally fixed getPitch method, it was rounding errors.
Sim: getPitch method now works …
> Various missile fixes and features.

- Mirage-2000/Models/Interior/Panel/Instruments/Mfd/mfdR.xml
- Mirage-2000/Models/Interior/Panel/Instruments/Mfd/mfd_cadre.ac
- Mirage-2000/Nasal/MFD/MAP.nas
- Mirage-2000/Nasal/RADAR/radar2.nas
- Mirage-2000/Nasal/RADAR/radarTool.nas
- Mirage-2000/Nasal/rwr.nas
- Mirage-2000/Systems/m2000-5-base.xml
Notice bug in radar2.nas, very important fix, its probably why your missiles do not work with Bombable anymore.
> RWR on MFD

- Mirage-2000/Models/Interior/Panel/Instruments/Mfd/mfdR.xml
- Mirage-2000/Nasal/MFD/MAP.nas
> Fixed the map

- Mirage-2000/Nasal/HUD/HUD.nas
- Mirage-2000/Nasal/RADAR/AIContact.nas
- Mirage-2000/gui/dialogs/options.xml
Implementation & integration of a closing speed indicator for the current locked target in the HUD.
resolves #87
> Canvas radar prototype

- Mirage-2000/Nasal/HUD/HUD.nas
The closing speed indicator is now positive when closing and negative when getting away.
> Changing the sign of the closing speed (positive is now closing).

- Mirage-2000/Nasal/HUD/HUD.nas
- Mirage-2000/Nasal/RADAR/AIContact.nas
- Mirage-2000/Nasal/vector.nas
The closing speed is now computed by projecting orthogonally the speed of the plane onto the line towards the target (the same is done from the target to the plane).
This means that AOA & sideslip are taken into consideration.
This also means that vertical speed is now included.
> Closing speed improvements.

- Mirage-2000/Systems/Mirage-2000-fcs.xml
> Setting the correct property for the right brake.

- Mirage-2000/Nasal/pylons.nas
> Previous one was false alarm. fixed this here

- Mirage-2000/gui/dialogs/config.xml
im so ready to go to bed oh wait no its still 16:30
> changed config as well

- Mirage-2000/Nasal/missile_GroundTargeting.nas
> Increase "ground target"

- Mirage-2000/gui/dialogs/config.xml
left column (0) is Air to Air while right (1) is all Air to Surface
> reordering the presets

- Mirage-2000/Nasal/pylons.nas
Got rid of mica em and mica ir for magic ii
> Reworked presets for "Standoff"

- Mirage-2000/Dialogs/m2000-5-menu.xml
- Mirage-2000/Models/External-objects/loads_models.xml
- Mirage-2000/Nasal/pylons.nas
- Mirage-2000/gui/dialogs/config.xml
- Mirage-2000/gui/dialogs/payload-5.xml
- Mirage-2000/gui/dialogs/payload-d.xml
- Mirage-2000/m2000-5-set.xml
- Mirage-2000/m2000-5B-set.xml
- Mirage-2000/m2000D-set.xml
Changelog:
- make individual Payload Quick select dialog for -5(B) and D/N
- seperate D from -5B, 
- remove MICA-IR from D
- fix exocet y location
> Split -5B and D model

- Mirage-2000/Nasal/missile-code.nas
- Mirage-2000/Nasal/vector.nas
- Mirage-2000/gui/dialogs/config.xml
Resolves #131 .
Implement a more formal and less computation-hungry algorithm for the computation of the shortest distance between a missile and it's target.
> Missile - Target distance

- Mirage-2000/Nasal/missile-code.nas
Resolves #131 .
Fixes for the post-merge review discussed in the pull-request #132 .
> Missile - Target distance HotFix

- Mirage-2000/Nasal/crash-and-stress.nas
- Mirage-2000/Nasal/hackCanvas.nas
- Mirage-2000/Systems/m2000-5-base.xml
- Mirage-2000/Systems/m2000-5B-base.xml
Make aircraft crash if hit ground.
> Improve canvas performance.

- Mirage-2000/gui/dialogs/payload-d.xml
Unguided and retarded options. should not destroy jmavs updates
> Fast rearm update for D

- Mirage-2000/Models/Logos/greece.xml
Changed "Greek" to "Hellenic".
> Έλληνεςςςςςςςςςςςςς

- Mirage-2000/gui/dialogs/event-log.xml
And improves refresh button.
Before
After
> Makes combat log window resizeable.

- Mirage-2000/Dialogs/m2000-5-menu.xml
- Mirage-2000/Mirage2000-vsp.xml
- Mirage-2000/Models/main.xml
- Mirage-2000/Systems/m2000-common.xml
- Mirage-2000/Systems/pushback.xml
Add a simple pushback system.
This uses FG's built in pushback system and 3D model.
This is how the pushback works with the engine off.
https://user-images.githubusercontent.com/6201512/132910514-c398a217-8746-4426-813f-b0d869b78cc8.mp4
And here with the engine running.
https://user-images.githubusercontent.com/6201512/132954314-d42a12c4-0453-44ce-9bf2-6bdb041428cc.mp4
> Add a pushback.
